# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import queries_db
from visualization import create_bar_plot


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 851, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.output_window = QtWidgets.QTextBrowser(self.tab)
        self.output_window.setGeometry(QtCore.QRect(530, 90, 256, 301))
        self.output_window.setObjectName("output_window")
        self.alliance_rb = QtWidgets.QRadioButton(self.tab)
        self.alliance_rb.setGeometry(QtCore.QRect(70, 220, 16, 16))
        self.alliance_rb.setText("")
        self.alliance_rb.setChecked(False)
        self.alliance_rb.setObjectName("alliance_rb")
        self.country_rb = QtWidgets.QRadioButton(self.tab)
        self.country_rb.setGeometry(QtCore.QRect(70, 130, 16, 16))
        self.country_rb.setText("")
        self.country_rb.setChecked(False)
        self.country_rb.setObjectName("country_rb")
        self.calculate_pushbutton = QtWidgets.QPushButton(self.tab)
        self.calculate_pushbutton.setGeometry(QtCore.QRect(210, 420, 121, 61))
        self.calculate_pushbutton.setObjectName("calculate_pushbutton")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 100, 351, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.overall_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.overall_label.setObjectName("overall_label")
        self.gridLayout.addWidget(self.overall_label, 4, 0, 1, 1)
        self.overall_cB = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overall_cB.setObjectName("overall_cB")
        self.gridLayout.addWidget(self.overall_cB, 5, 0, 1, 1)
        self.alliance_fun_cB = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.alliance_fun_cB.setObjectName("alliance_fun_cB")
        self.gridLayout.addWidget(self.alliance_fun_cB, 3, 1, 1, 1)
        self.country_fun_cB = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.country_fun_cB.setObjectName("country_fun_cB")
        self.gridLayout.addWidget(self.country_fun_cB, 1, 1, 1, 1)
        self.alliance_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.alliance_label.setObjectName("alliance_label")
        self.gridLayout.addWidget(self.alliance_label, 2, 0, 1, 1)
        self.country_cB = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.country_cB.setObjectName("country_cB")
        self.gridLayout.addWidget(self.country_cB, 1, 0, 1, 1)
        self.alliance_cB = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.alliance_cB.setObjectName("alliance_cB")
        self.gridLayout.addWidget(self.alliance_cB, 3, 0, 1, 1)
        self.country_fun_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.country_fun_label.setObjectName("country_fun_label")
        self.gridLayout.addWidget(self.country_fun_label, 0, 1, 1, 1)
        self.country_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.country_label.setObjectName("country_label")
        self.gridLayout.addWidget(self.country_label, 0, 0, 1, 1)
        self.alliance_fun_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.alliance_fun_label.setObjectName("alliance_fun_label")
        self.gridLayout.addWidget(self.alliance_fun_label, 2, 1, 1, 1)
        self.overall_rb = QtWidgets.QRadioButton(self.tab)
        self.overall_rb.setGeometry(QtCore.QRect(70, 310, 16, 16))
        self.overall_rb.setText("")
        self.overall_rb.setChecked(True)
        self.overall_rb.setObjectName("overall_rb")
        self.draw_pushbutton = QtWidgets.QPushButton(self.tab)
        self.draw_pushbutton.setGeometry(QtCore.QRect(600, 420, 121, 61))
        self.draw_pushbutton.setObjectName("draw_pushbutton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        # Comboboxes setup
        self.country_cB.addItems(queries_db.get_all_countries())
        self.country_fun_cB.addItems(["Tanks quantity", "Alliances involvment", "Tanks orgin"])
        self.country_cB.currentTextChanged.connect(self.deactive_plot_button)
        self.country_fun_cB.currentTextChanged.connect(self.deactive_plot_button)
        self.alliance_cB.addItems(queries_db.get_all_alliances())
        self.alliance_fun_cB.addItems(["Tanks quantity", "Member countries", "Tanks orgin"])
        self.alliance_cB.currentTextChanged.connect(self.deactive_plot_button)
        self.alliance_fun_cB.currentTextChanged.connect(self.deactive_plot_button)

        self.overall_cB.addItems(["Most popular tanks", "Biggest sellers", "Strongest alliances"])
        self.overall_cB.currentTextChanged.connect(self.deactive_plot_button)

        #BrowserText setup
        self.output_window.horizontalScrollBar().setValue(0)
        self.output_window.setLineWrapMode(0)
        # Button setup
        self.calculate_pushbutton.clicked.connect(self.on_click_calcualte_button)

        self.draw_pushbutton.setDisabled(True)
        self.draw_pushbutton.clicked.connect(self.on_click_draw_button)
        #Font setup
        font = QtGui.QFont("Monospace")
        font.setStyleHint(QtGui.QFont.TypeWriter)
        self.output_window.setFont(font)

    def on_click_calcualte_button(self):
        self.draw_pushbutton.setDisabled(False)
        if self.country_rb.isChecked():
            text = str(self.country_cB.currentText())
            function = self.country_fun_cB.currentIndex()
            if function == 0:
                self.output_window.setText(str(queries_db.country_tank_info(text, formated = True)))
            if function == 1:
                self.output_window.setText(str(queries_db.country_aliance_info(text, formated = True)))
            if function == 2:
                self.output_window.setText(str(queries_db.country_tank_seller_origin_info(text, formated = True)))
        if self.alliance_rb.isChecked():
            text = str(self.alliance_cB.currentText())
            function = self.alliance_fun_cB.currentIndex()
            if function == 0:
                self.output_window.setText(str(queries_db.alliance_tanks_info(text, formated = True, max_end_date=1900)))
            if function == 1:
                self.output_window.setText(str(queries_db.alliance_countries_info(text, formated = True)))
            if function == 2:
                self.output_window.setText(str(queries_db.alliance_tanks_origin_info(text, formated = True)))
        if self.overall_rb.isChecked():
            function = self.overall_cB.currentIndex()
            if function == 0:
                self.output_window.setText(str(queries_db.overall_tanks_quantity(formated = True)))
            if function == 1:
                self.output_window.setText(str(queries_db.overall_orgin_quantity(formated = True)))
            if function == 2:
                self.output_window.setText(str(queries_db.overall_alliances_tank_quantity(formated = True)))

    def on_click_draw_button(self):
        x = queries_db.overall_tanks_quantity()
        
        create_bar_plot(x, "Overall tank quantity")

    def deactive_plot_button(self):
        self.draw_pushbutton.setDisabled(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.calculate_pushbutton.setText(_translate("MainWindow", "Calculate!"))
        self.overall_label.setText(_translate("MainWindow", "Additional statistics"))
        self.alliance_label.setText(_translate("MainWindow", "Choose alliance:"))
        self.country_fun_label.setText(_translate("MainWindow", "Choose function"))
        self.country_label.setText(_translate("MainWindow", "Choose country:"))
        self.alliance_fun_label.setText(_translate("MainWindow", "Choose function"))
        self.draw_pushbutton.setText(_translate("MainWindow", "Create plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Basic functions"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


if __name__ == '__main__':
    import sys
    x = queries_db.alliance_tanks_info("Crusades", formated = True, max_end_date=1900)
    app = QtWidgets.QApplication([])
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())